### ISSUE TITLE
Cannot login using Firefox

### ISSUE THREAD

**Issue by nikolayhg** [Graphite-Docs/graphite#137]
I cannot login using Firefox 64 on Ubuntu 18.04:

1. Open https://app.graphitedocs.com/
2. Click the sign-in button
3. Nothing happens. Screenshot: https://i.imgur.com/0gAvoKU.png

Console output:
```
Unhandled promise rejection TypeError: "e is null"
	p https://app.graphitedocs.com/static/js/main.26b768ef.js:136:702676
	getOrSetLocalGaiaHubConnection https://app.graphitedocs.com/static/js/main.26b768ef.js:136:700830
	m https://app.graphitedocs.com/static/js/main.26b768ef.js:54:677174
	a https://app.graphitedocs.com/static/js/main.26b768ef.js:80:97934
	I https://app.graphitedocs.com/static/js/main.26b768ef.js:80:98056
	c https://app.graphitedocs.com/static/js/main.26b768ef.js:86:32103
main.26b768ef.js:80:98291
New content is available and will be used when all tabs for this page are closed. See http://bit.ly/CRA-PWA. main.26b768ef.js:839:123605
[INFO] blockstack.js: generating v1.3.0 auth request main.26b768ef.js:19:341128
openUriUsingFirefox main.26b768ef.js:136:354604
[INFO] protocol handler detected
```

**Comment by jhunter5811** [comment]
Blockstack's protocol handler has trouble with Ubuntu and Firefox. Firefox requires you to run a local install of the Blockstack Browser. So that should be your first step if you're not already doing it. You can install it here: 

https://blockstack.org/install

As for using Blockstack apps with Ubuntu, this forum thread should still apply: 

https://forum.blockstack.org/t/linux-walkthrough/2495

**Comment by nikolayhg** [comment]
thanks!
