### ISSUE TITLE
BUG - Export: links duplicated

### ISSUE THREAD

**Issue by raiseandfall** [Graphite-Docs/graphite#32]
### Bug description
This is not blocking, just impacting performance. I noticed it while testing #16. The two downloads links will get rendered as many times as `render()` is getting invoked (over a dozen times), which pollutes the DOM tree.

### Steps to reproduce
- Go to "export all data"

### Fix description
Move links generation in a separate function that will be invoked once & as soon as state is available.

**Comment by jehunter5811** [comment]
Thanks, @raiseandfall! This one needs a complete reworking, which is why it hasn't been touched. The original design of Graphite was a single file containing all documents. This export function was a relic of that time. It needs to be updated to use the new index/individual files structure to build up a single json export. Hope to work on that this week.
